"""add reason to walker_adhoc_availability

Revision ID: 0b555201bd02
Revises: c3f1a8b29e4d
Create Date: 2026-05-13 12:24:53.592979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b555201bd02'
down_revision = 'c3f1a8b29e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walker_adhoc_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walker_adhoc_availability', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
