"""add slot_freezes table

Revision ID: 0f9a3eb9bc78
Revises: 620941797ef0
Create Date: 2026-09-06 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f9a3eb9bc78'
down_revision = '620941797ef0'
branch_labels = None
depends_on = None

# Reference existing enum — don't create it
schedule_slot = postgresql.ENUM('Morning', 'Afternoon', name='schedule_slot', create_type=False)


def upgrade():
    op.create_table('slot_freezes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slot', schedule_slot, nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('range_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'slot', name='uq_slot_freeze_date_slot')
    )
    with op.batch_alter_table('slot_freezes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slot_freezes_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_slot_freezes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_slot_freezes_range_id'), ['range_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slot_freezes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slot_freezes_range_id'))
        batch_op.drop_index(batch_op.f('ix_slot_freezes_created_at'))
        batch_op.drop_index(batch_op.f('ix_slot_freezes_date'))

    op.drop_table('slot_freezes')
    # ### end Alembic commands ###
