"""increase pickup_instructions to 1000 chars

Revision ID: 366907dd88dc
Revises: d0b322310985
Create Date: 2026-04-27 20:24:41.299891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366907dd88dc'
down_revision = 'd0b322310985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.alter_column('pickup_instructions',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.alter_column('pickup_instructions',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
