"""add pricing_configs table

Revision ID: 675836a4fb0f
Revises: 9676d6cb9ca6
Create Date: 2026-03-10 15:31:31.446163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675836a4fb0f'
down_revision = '9676d6cb9ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_per_walk', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('double_slot_discount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('effective_from')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_configs')
    # ### end Alembic commands ###
