"""add whatsapp_group_url to dogs

Revision ID: 6a578a1aa990
Revises: f6c014e65b04
Create Date: 2026-03-22 12:19:10.145743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a578a1aa990'
down_revision = 'f6c014e65b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_group_url', sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_group_url')

    # ### end Alembic commands ###
