"""add broadcasts table

Revision ID: 6c2e474e3b02
Revises: 0b555201bd02
Create Date: 2026-05-21 09:01:18.660598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2e474e3b02'
down_revision = '0b555201bd02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('scope_date', sa.Date(), nullable=False),
    sa.Column('scope_slot', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('bell_sent', sa.Boolean(), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broadcasts_scope_date'), ['scope_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_broadcasts_sent_at'), ['sent_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broadcasts_sent_at'))
        batch_op.drop_index(batch_op.f('ix_broadcasts_scope_date'))

    op.drop_table('broadcasts')
    # ### end Alembic commands ###
