"""Add unique partial index to prevent duplicate active bookings

Revision ID: 74a5d839976a
Revises: 37084a06d693
Create Date: 2026-03-05 04:01:10.908089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a5d839976a'
down_revision = '37084a06d693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index('ix_booking_dog_date_slot_active', ['dog_id', 'date', 'slot'], unique=True, postgresql_where=sa.text("status NOT IN ('cancelled', 'rejected', 'completed')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('ix_booking_dog_date_slot_active', postgresql_where=sa.text("status NOT IN ('cancelled', 'rejected', 'completed')"))

    # ### end Alembic commands ###
