"""add daily_messages table

Revision ID: bb01daed9dde
Revises: 03cc1232ef8f
Create Date: 2026-04-13 14:53:12.544672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb01daed9dde'
down_revision = '03cc1232ef8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_messages_date'), ['date'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_messages_date'))

    op.drop_table('daily_messages')
    # ### end Alembic commands ###
