"""Add indexes on frequently queried columns

Revision ID: cecfaed20a55
Revises: c42536345bb9
Create Date: 2026-02-23 18:54:54.023013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecfaed20a55'
down_revision = 'c42536345bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_walker_id'), ['walker_id'], unique=False)

    with op.batch_alter_table('dog_owners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dog_owners_dog_id'), ['dog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dog_owners_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('walker_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_walker_schedules_walker_id'), ['walker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walker_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_walker_schedules_walker_id'))

    with op.batch_alter_table('dog_owners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dog_owners_user_id'))
        batch_op.drop_index(batch_op.f('ix_dog_owners_dog_id'))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_walker_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_date'))

    # ### end Alembic commands ###
