"""add composite index on bookings date slot status

Revision ID: d1c45fb8dbff
Revises: c3e7f1a2d890
Create Date: 2026-04-22 13:33:22.637975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c45fb8dbff'
down_revision = 'c3e7f1a2d890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index('ix_booking_date_slot_status', ['date', 'slot', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('ix_booking_date_slot_status')

    # ### end Alembic commands ###
