"""Remove firstname and lastname from Walker model

Revision ID: eefef29d7733
Revises: 
Create Date: 2025-08-24 18:31:11.074668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eefef29d7733'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walkers', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walkers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
