"""move pickup_instructions from clients to dogs

Revision ID: f1bfa22e3f85
Revises: faf8e45aafc5
Create Date: 2026-04-06 19:55:20.083191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bfa22e3f85'
down_revision = 'faf8e45aafc5'
branch_labels = None
depends_on = None


def upgrade():
    # Add the new column to dogs first
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_instructions', sa.String(length=500), nullable=True))

    # Copy pickup notes from each client to their primary dog (before dropping the source column)
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE dogs
        SET pickup_instructions = sub.pickup_instructions
        FROM (
            SELECT own.dog_id, c.pickup_instructions
            FROM clients c
            JOIN dog_owners own ON own.user_id = c.user_id AND own.role = 'primary'
            WHERE c.pickup_instructions IS NOT NULL
        ) sub
        WHERE dogs.id = sub.dog_id
    """))

    # Now drop the column from clients
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('pickup_instructions')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_column('pickup_instructions')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_instructions', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
