"""add walker_adhoc_availability table

Revision ID: faf8e45aafc5
Revises: 57c20fea3655
Create Date: 2026-04-05 17:08:00.949207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'faf8e45aafc5'
down_revision = '57c20fea3655'
branch_labels = None
depends_on = None

# Reference existing enum — don't create it
schedule_slot = postgresql.ENUM('Morning', 'Afternoon', name='schedule_slot', create_type=False)


def upgrade():
    op.create_table('walker_adhoc_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('walker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slot', schedule_slot, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['walker_id'], ['walkers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('walker_id', 'date', 'slot', name='uq_walker_adhoc_date_slot')
    )
    with op.batch_alter_table('walker_adhoc_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_walker_adhoc_availability_walker_id'), ['walker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walker_adhoc_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_walker_adhoc_availability_walker_id'))

    op.drop_table('walker_adhoc_availability')
    # ### end Alembic commands ###
